"use client";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* CDN for the model viewer */}
      {/* <script
        defer
        type="module"
        src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
      ></script> */}

      <body className={inter.className}>{children}</body>
    </html>
  );
}
